### ISSUE TITLE
Your build.yml is useful, could you make it a GH action?

### ISSUE THREAD

**Issue by HuJJ-NB** [bison-packages/packages#1]

**Comment by iliabylich** [comment]
like this https://github.com/bison-packages/install-bison ? 😄

**Comment by HuJJ-NB** [comment]
I find this repo by this action, but it can just download v3.8.2, I try to make your script work to build a bison-3.5.1, but can not make release.

Maybe there are some settings of GitHub I skipped.

**Comment by iliabylich** [comment]
Sorry, it's not clear from the README, but this repo exists to have pre-compiled packages as releases (so that "action" repo can quickly take them as is by downloading and unpacking).

I've pushed a tag for `v3.5.1` and this release [has been automatically created](https://github.com/bison-packages/packages/actions/runs/4636602076/jobs/8204654154) - https://github.com/bison-packages/packages/releases/tag/v3.5.1. Could you try passing `3.5.1` version again?

**Comment by iliabylich** [comment]
Closing. Please let me know if there's still something else that you need.

**Comment by HuJJ-NB** [comment]
thanks, it works
